sudo: required

services:
  - docker

## Make sure all containers build without error.
## r-devel times out on build, so just pull instead

before_install: 
  - docker build -t jrowen/dcaret .

## Crude test, see if our container stays up after launch
script:
  - docker run -ti jrowen/dcaret R --version
  - docker run -d --name rstudio jrowen/dcaret
  - sleep 5 && docker ps | grep dcaret
  - docker rm -f $(docker ps -a -q)
